name: Recolector SADI

on:
  schedule:
    - cron: '*/5 * * * *' # Ejecutar cada 5 minutos
  workflow_dispatch: # Permite ejecutar manualmente para probar

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests pandas

      - name: Correr script
        run: python bot.py

      - name: Guardar cambios
        run: |
          git config user.name "SadiBot"
          git config user.email "bot@users.noreply.github.com"
          git add sadi_historico.csv
          git commit -m "Actualización automática de datos" || exit 0
          git push
